//! Rig V1 runtime source — embedded as a Zig string constant and
//! written verbatim to `_rig_runtime.zig` next to each emitted module.
//!
//! Per the M20d design checkpoint with GPT-5.5 (conversation
//! `c_5c1d09d53ebe2f62`) plus the post-(1/5) review:
//!
//!   - `RcBox(T)` carries `allocator`, `strong: usize`, `weak: usize`,
//!     and the value. The implicit `+1` weak count keeps the control
//!     block alive while `strong > 0`. No mutable global allocator.
//!   - `WeakHandle(T)` is `?*RcBox(T)` with explicit clone/drop;
//!     `dropWeak` takes `*Self` so it can null the pointer defensively
//!     in case ownership tracking misses a double-drop.
//!   - Method names are EXPLICIT: `cloneStrong` / `dropStrong` /
//!     `cloneWeak` / `dropWeak` / `weakRef` / `upgrade`. This is for
//!     readability of emitted Zig — emitted `rc.cloneStrong()` reads
//!     unambiguously vs `rc.clone()` which would be confusable with
//!     library-defined clones for other types.
//!   - `rcNew(anytype)` is the constructor helper the emitter calls for
//!     `*expr`. It uses `defaultAllocator()` so the emitter doesn't need
//!     expression-type info to construct an `RcBox`.
//!   - V1 has no user `Drop` and no auto-drop. Strong-to-zero frees
//!     the value's slot but does not run user destructors. M20e adds
//!     compiler-synthesized scope-exit drops.
//!
//! The source is kept here as a single `pub const source: []const u8`
//! so the driver can write it byte-for-byte to the output directory
//! without any build-time path coordination. Editing this file changes
//! the runtime that ships with the next emit.

pub const filename = "_rig_runtime.zig";

pub const source =
    \\//! Rig V1 runtime — generated by `bin/rig build`/`run`. Do not edit.
    \\//!
    \\//! Single-threaded `Rc<T>` / `Weak<T>` with explicit reference-count
    \\//! operations. V1 requires explicit `-rc` / `-w` to drop; automatic
    \\//! scope-exit drop is planned for M20e (before closure capture).
    \\
    \\const std = @import("std");
    \\
    \\/// Reference-counted box. `strong` counts owning handles; `weak`
    \\/// counts weak handles plus an implicit `+1` while `strong > 0` to
    \\/// keep the control block alive for weak-holders even after the
    \\/// value is logically gone.
    \\pub fn RcBox(comptime T: type) type {
    \\    return struct {
    \\        allocator: std.mem.Allocator,
    \\        strong: usize,
    \\        weak: usize,
    \\        value: T,
    \\
    \\        const Self = @This();
    \\
    \\        pub fn new(allocator: std.mem.Allocator, value: T) !*Self {
    \\            const box = try allocator.create(Self);
    \\            box.* = .{
    \\                .allocator = allocator,
    \\                .strong = 1,
    \\                .weak = 1, // implicit +1 while strong > 0
    \\                .value = value,
    \\            };
    \\            return box;
    \\        }
    \\
    \\        /// Increment strong count and return the same handle. Pairs
    \\        /// with an eventual `dropStrong`. Asserts the handle is alive.
    \\        pub fn cloneStrong(self: *Self) *Self {
    \\            std.debug.assert(self.strong > 0);
    \\            self.strong += 1;
    \\            return self;
    \\        }
    \\
    \\        /// Construct a weak handle. Increments the weak count.
    \\        /// Asserts a live strong count.
    \\        pub fn weakRef(self: *Self) WeakHandle(T) {
    \\            std.debug.assert(self.strong > 0);
    \\            self.weak += 1;
    \\            return .{ .ptr = self };
    \\        }
    \\
    \\        /// Decrement strong count. When it reaches zero, release the
    \\        /// implicit weak `+1`; if weak also reaches zero (no live weak
    \\        /// handles), free the box.
    \\        ///
    \\        /// V1: does NOT run a user-defined destructor on `value`. M20e
    \\        /// or later adds the Drop hook.
    \\        pub fn dropStrong(self: *Self) void {
    \\            std.debug.assert(self.strong > 0);
    \\            self.strong -= 1;
    \\            if (self.strong == 0) {
    \\                // Future: run user-defined Drop on `self.value` here.
    \\                self.weak -= 1; // release implicit +1
    \\                if (self.weak == 0) self.allocator.destroy(self);
    \\            }
    \\        }
    \\    };
    \\}
    \\
    \\/// Weak handle paired with `*T = RcBox(T)`. Holds an optional
    \\/// pointer; `null` after `dropWeak`. Does NOT keep `T` alive.
    \\pub fn WeakHandle(comptime T: type) type {
    \\    return struct {
    \\        ptr: ?*RcBox(T),
    \\
    \\        const Self = @This();
    \\
    \\        /// Increment weak count, return a new handle aliasing the
    \\        /// same control block. Safe when `ptr == null` (returns null).
    \\        pub fn cloneWeak(self: Self) Self {
    \\            if (self.ptr) |p| p.weak += 1;
    \\            return self;
    \\        }
    \\
    \\        /// Decrement weak count. When BOTH weak and strong reach
    \\        /// zero, free the box. Takes `Self` by value so weak
    \\        /// bindings can be emitted as `const` Zig (the original
    \\        /// design used `*Self` for defensive nulling, but Rig's
    \\        /// ownership pass already errors on `-w; -w` — see
    \\        /// `src/ownership.zig`'s `walkDrop`. Defensive nulling
    \\        /// without ownership integration would just paper over
    \\        /// bugs in the checker, and adding `var`-vs-`const` emit
    \\        /// rules for weak bindings adds complexity for no real
    \\        /// safety gain once the ownership invariant is upheld).
    \\        pub fn dropWeak(self: Self) void {
    \\            if (self.ptr) |p| {
    \\                std.debug.assert(p.weak > 0);
    \\                p.weak -= 1;
    \\                if (p.weak == 0 and p.strong == 0) p.allocator.destroy(p);
    \\            }
    \\        }
    \\
    \\        /// Attempt to obtain a fresh strong handle. Returns `null` if
    \\        /// the value has been dropped (`strong == 0`) or this weak
    \\        /// handle was nulled. On success, increments the strong count.
    \\        pub fn upgrade(self: Self) ?*RcBox(T) {
    \\            const p = self.ptr orelse return null;
    \\            if (p.strong == 0) return null;
    \\            p.strong += 1;
    \\            return p;
    \\        }
    \\    };
    \\}
    \\
    \\/// Cell(T) — interior mutability for Copy T. M20f.
    \\///
    \\/// `set(self: *Self, value: T)` mutates through a mutable pointer.
    \\/// Bindings of type `Cell(T)` are emitted as Zig `var` so the
    \\/// pointer is valid. For `*Cell(T)` (shared cell), the `RcBox`'s
    \\/// `.value` field is mutable through the strong handle, so the
    \\/// pointer-to-mutable path works through M20d's auto-deref.
    \\///
    \\/// V1 restricts `T` to Copy types (Int, Bool, Float, String,
    \\/// literal pseudo-types) at the sema layer. Non-Copy T would
    \\/// allow ownership corruption (`Cell(*User).set` would overwrite
    \\/// without dropping the previous handle); revisit when V1 grows
    \\/// proper replace/take semantics + user Drop.
    \\pub fn Cell(comptime T: type) type {
    \\    return struct {
    \\        value: T,
    \\
    \\        const Self = @This();
    \\
    \\        pub fn new(initial: T) Self {
    \\            return .{ .value = initial };
    \\        }
    \\
    \\        pub fn get(self: Self) T {
    \\            return self.value;
    \\        }
    \\
    \\        pub fn set(self: *Self, value: T) void {
    \\            self.value = value;
    \\        }
    \\    };
    \\}
    \\
    \\/// V1 default allocator for `*expr` boxes. Single-threaded, page-
    \\/// based. Later milestones may surface an allocator parameter; for
    \\/// V1 the runtime hides the choice so `*expr` is a one-liner in
    \\/// emitted Zig.
    \\pub fn defaultAllocator() std.mem.Allocator {
    \\    return std.heap.page_allocator;
    \\}
    \\
    \\/// Construct an `RcBox(T)` from a value, using the default allocator.
    \\/// Called by the emitter for `*expr` — the surrounding catch turns
    \\/// allocation failure into a panic (per the M20d design pass).
    \\pub fn rcNew(value: anytype) !*RcBox(@TypeOf(value)) {
    \\    return RcBox(@TypeOf(value)).new(defaultAllocator(), value);
    \\}
    \\
;
