//! Rig V1 runtime source — embedded as a Zig string constant and
//! written verbatim to `_rig_runtime.zig` next to each emitted module.
//!
//! Per the M20d design checkpoint with GPT-5.5 (conversation
//! `c_5c1d09d53ebe2f62`) plus the post-(1/5) review:
//!
//!   - `RcBox(T)` carries `allocator`, `strong: usize`, `weak: usize`,
//!     and the value. The implicit `+1` weak count keeps the control
//!     block alive while `strong > 0`. No mutable global allocator.
//!   - `WeakHandle(T)` is `?*RcBox(T)` with explicit clone/drop;
//!     `dropWeak` takes `*Self` so it can null the pointer defensively
//!     in case ownership tracking misses a double-drop.
//!   - Method names are EXPLICIT: `cloneStrong` / `dropStrong` /
//!     `cloneWeak` / `dropWeak` / `weakRef` / `upgrade`. This is for
//!     readability of emitted Zig — emitted `rc.cloneStrong()` reads
//!     unambiguously vs `rc.clone()` which would be confusable with
//!     library-defined clones for other types.
//!   - `rcNew(anytype)` is the constructor helper the emitter calls for
//!     `*expr`. It uses `defaultAllocator()` so the emitter doesn't need
//!     expression-type info to construct an `RcBox`.
//!   - V1 has no user `Drop` and no auto-drop. Strong-to-zero frees
//!     the value's slot but does not run user destructors. M20e adds
//!     compiler-synthesized scope-exit drops.
//!
//! Per the M20h design checkpoint with GPT-5.5 (entry 17):
//!
//!   - `Closure0` is the type-erased no-arg/void-return closure ABI.
//!     A vtable struct carrying `ctx: *anyopaque`, `invoke_fn`,
//!     `drop_fn`, and `allocator`. Each closure literal generates a
//!     unique env struct holding captures + invoke/drop thunks; the
//!     env is heap-allocated SEPARATELY from the surrounding `RcBox`
//!     and freed by `drop_fn` when the closure's strong count hits
//!     zero. The type erasure (uniform `Closure0` surface for all
//!     closure literals) is what makes `*Closure()` a real handle —
//!     returnable from functions, storable in struct fields, etc.
//!   - `RcBox(T).dropStrong()` runs `T.__rig_drop(&self.value)` on
//!     last strong when `T` declares it. This is the hook closures
//!     use to drop their captures + free the env at the right
//!     moment. Other payload types are unaffected.
//!   - `hasRigDrop(T)` is a `comptime` predicate that only inspects
//!     containers (`struct`/`union`/`enum`/`opaque`). Primitives like
//!     `i32` lack the `@hasDecl` syntax, so the helper avoids any
//!     Zig-version surprises.
//!
//! Per the M20i design checkpoint with GPT-5.5 (entry 24):
//!
//!   - `Vec(T)` is the resource-aware container — the first user-
//!     facing builtin OWNING value type beyond `*T`/`~T` handles. It
//!     itself owns a heap-allocated buffer plus tracks `len`/`cap`/
//!     `allocator`. Bare copy is unsafe (would double-free the
//!     buffer); the sema layer enforces "no bare copy/alias" + "move
//!     via `<vec`" + "explicit drop via `-vec`" + "auto-drop guard
//!     at scope exit" (M20i sub-commits (2-3/5)).
//!   - `Vec(T)` element kinds in V1: Copy primitives, `*T` shared
//!     handles, `~T` weak handles, `*Closure()`. Arbitrary nominal
//!     T is rejected until user-defined Drop exists.
//!   - `dropElement(comptime T, *T)` is the runtime helper that
//!     knows how to drop a Vec element by inspecting the element
//!     type at comptime. Uses a hybrid dispatch:
//!       1. `*RcBox(U)` (strong handle, a pointer type) →
//!          `dropStrong()`. Detected via `__rig_rcbox_marker` on
//!          the pointee. Pointer types can't declare `__rig_drop`,
//!          so the marker-based path is necessary.
//!       2. Anything with `__rig_drop` (weak handles, closures,
//!          future user types) → call it.
//!       3. Else (Copy primitives) → no-op.
//!     The markers (`__rig_rcbox_marker`, `__rig_weak_marker`,
//!     `__rig_vec_marker`) are comptime decls used ONLY for shape
//!     dispatch; no runtime cost.
//!
//! The source is kept here as a single `pub const source: []const u8`
//! so the driver can write it byte-for-byte to the output directory
//! without any build-time path coordination. Editing this file changes
//! the runtime that ships with the next emit.

pub const filename = "_rig_runtime.zig";

pub const source =
    \\//! Rig V1 runtime — generated by `bin/rig build`/`run`. Do not edit.
    \\//!
    \\//! Single-threaded `Rc<T>` / `Weak<T>` with explicit reference-count
    \\//! operations. V1 requires explicit `-rc` / `-w` to drop; automatic
    \\//! scope-exit drop is planned for M20e (before closure capture).
    \\
    \\const std = @import("std");
    \\
    \\/// Compile-time predicate: does `T` declare `__rig_drop`?
    \\///
    \\/// Used by `RcBox(T).dropStrong()` to invoke a payload's
    \\/// destructor hook on last-strong-drop. Only container kinds
    \\/// (struct/union/enum/opaque) can declare functions, so for
    \\/// primitive payloads (`i32`, `bool`, etc.) the answer is
    \\/// always `false`. Wrapping `@hasDecl` in this switch makes
    \\/// the runtime robust to Zig-version differences in how
    \\/// `@hasDecl` handles non-container types.
    \\pub fn hasRigDrop(comptime T: type) bool {
    \\    return switch (@typeInfo(T)) {
    \\        .@"struct", .@"union", .@"enum", .@"opaque" => @hasDecl(T, "__rig_drop"),
    \\        else => false,
    \\    };
    \\}
    \\
    \\/// Reference-counted box. `strong` counts owning handles; `weak`
    \\/// counts weak handles plus an implicit `+1` while `strong > 0` to
    \\/// keep the control block alive for weak-holders even after the
    \\/// value is logically gone.
    \\pub fn RcBox(comptime T: type) type {
    \\    return struct {
    \\        allocator: std.mem.Allocator,
    \\        strong: usize,
    \\        weak: usize,
    \\        value: T,
    \\
    \\        /// M20i: marker for the `dropElement` hybrid dispatch.
    \\        /// `*RcBox(U)` is a POINTER type — pointer types can't
    \\        /// declare `__rig_drop`, so we use shape-based dispatch
    \\        /// on the pointee. The marker is a comptime decl with
    \\        /// no runtime cost.
    \\        pub const __rig_rcbox_marker = true;
    \\        pub const __rig_child = T;
    \\
    \\        const Self = @This();
    \\
    \\        pub fn new(allocator: std.mem.Allocator, value: T) !*Self {
    \\            const box = try allocator.create(Self);
    \\            box.* = .{
    \\                .allocator = allocator,
    \\                .strong = 1,
    \\                .weak = 1, // implicit +1 while strong > 0
    \\                .value = value,
    \\            };
    \\            return box;
    \\        }
    \\
    \\        /// Increment strong count and return the same handle. Pairs
    \\        /// with an eventual `dropStrong`. Asserts the handle is alive.
    \\        pub fn cloneStrong(self: *Self) *Self {
    \\            std.debug.assert(self.strong > 0);
    \\            self.strong += 1;
    \\            return self;
    \\        }
    \\
    \\        /// Construct a weak handle. Increments the weak count.
    \\        /// Asserts a live strong count.
    \\        pub fn weakRef(self: *Self) WeakHandle(T) {
    \\            std.debug.assert(self.strong > 0);
    \\            self.weak += 1;
    \\            return .{ .ptr = self };
    \\        }
    \\
    \\        /// Decrement strong count. When it reaches zero, run the
    \\        /// payload's `__rig_drop` (if it declares one), then release
    \\        /// the implicit weak `+1`; if weak also reaches zero (no
    \\        /// live weak handles), free the box.
    \\        ///
    \\        /// `__rig_drop(&self.value)` runs while the RcBox is still
    \\        /// valid and `strong == 0` — meaning any weak-upgrade
    \\        /// attempt from inside the destructor (or from another
    \\        /// thread, future-multithreading) will correctly fail.
    \\        /// This is the M20h hook used by `Closure0` to free its
    \\        /// heap-allocated env + drop captured resources.
    \\        ///
    \\        /// Containers without `__rig_drop` (the M20a-M20g cases)
    \\        /// short-circuit on the comptime branch — no runtime cost.
    \\        pub fn dropStrong(self: *Self) void {
    \\            std.debug.assert(self.strong > 0);
    \\            self.strong -= 1;
    \\            if (self.strong == 0) {
    \\                if (comptime hasRigDrop(T)) self.value.__rig_drop();
    \\                self.weak -= 1; // release implicit +1
    \\                if (self.weak == 0) self.allocator.destroy(self);
    \\            }
    \\        }
    \\    };
    \\}
    \\
    \\/// Weak handle paired with `*T = RcBox(T)`. Holds an optional
    \\/// pointer; `null` after `dropWeak`. Does NOT keep `T` alive.
    \\pub fn WeakHandle(comptime T: type) type {
    \\    return struct {
    \\        ptr: ?*RcBox(T),
    \\
    \\        /// M20i: marker + `__rig_drop` hook so `dropElement`
    \\        /// can dispatch on weak handles uniformly. Weak handles
    \\        /// are STRUCT values (not pointers), so they CAN
    \\        /// declare `__rig_drop` directly.
    \\        pub const __rig_weak_marker = true;
    \\
    \\        const Self = @This();
    \\
    \\        /// M20i: standard destructor hook \u2014 invoked by
    \\        /// `dropElement` when a `Vec(~T)` element is dropped.
    \\        /// Identical to `dropWeak`. Named separately so the
    \\        /// `__rig_drop` convention is consistent across all
    \\        /// droppable types in the runtime (`Closure0`,
    \\        /// `Vec(T)`, `WeakHandle(T)`).
    \\        pub fn __rig_drop(self: *Self) void {
    \\            self.*.dropWeak();
    \\        }
    \\
    \\        /// Increment weak count, return a new handle aliasing the
    \\        /// same control block. Safe when `ptr == null` (returns null).
    \\        pub fn cloneWeak(self: Self) Self {
    \\            if (self.ptr) |p| p.weak += 1;
    \\            return self;
    \\        }
    \\
    \\        /// Decrement weak count. When BOTH weak and strong reach
    \\        /// zero, free the box. Takes `Self` by value so weak
    \\        /// bindings can be emitted as `const` Zig (the original
    \\        /// design used `*Self` for defensive nulling, but Rig's
    \\        /// ownership pass already errors on `-w; -w` — see
    \\        /// `src/ownership.zig`'s `walkDrop`. Defensive nulling
    \\        /// without ownership integration would just paper over
    \\        /// bugs in the checker, and adding `var`-vs-`const` emit
    \\        /// rules for weak bindings adds complexity for no real
    \\        /// safety gain once the ownership invariant is upheld).
    \\        pub fn dropWeak(self: Self) void {
    \\            if (self.ptr) |p| {
    \\                std.debug.assert(p.weak > 0);
    \\                p.weak -= 1;
    \\                if (p.weak == 0 and p.strong == 0) p.allocator.destroy(p);
    \\            }
    \\        }
    \\
    \\        /// Attempt to obtain a fresh strong handle. Returns `null` if
    \\        /// the value has been dropped (`strong == 0`) or this weak
    \\        /// handle was nulled. On success, increments the strong count.
    \\        pub fn upgrade(self: Self) ?*RcBox(T) {
    \\            const p = self.ptr orelse return null;
    \\            if (p.strong == 0) return null;
    \\            p.strong += 1;
    \\            return p;
    \\        }
    \\    };
    \\}
    \\
    \\/// Cell(T) — interior mutability for Copy T. M20f.
    \\///
    \\/// `set(self: *Self, value: T)` mutates through a mutable pointer.
    \\/// Bindings of type `Cell(T)` are emitted as Zig `var` so the
    \\/// pointer is valid. For `*Cell(T)` (shared cell), the `RcBox`'s
    \\/// `.value` field is mutable through the strong handle, so the
    \\/// pointer-to-mutable path works through M20d's auto-deref.
    \\///
    \\/// V1 restricts `T` to Copy types (Int, Bool, Float, String,
    \\/// literal pseudo-types) at the sema layer. Non-Copy T would
    \\/// allow ownership corruption (`Cell(*User).set` would overwrite
    \\/// without dropping the previous handle); revisit when V1 grows
    \\/// proper replace/take semantics + user Drop.
    \\pub fn Cell(comptime T: type) type {
    \\    return struct {
    \\        value: T,
    \\
    \\        const Self = @This();
    \\
    \\        pub fn new(initial: T) Self {
    \\            return .{ .value = initial };
    \\        }
    \\
    \\        pub fn get(self: Self) T {
    \\            return self.value;
    \\        }
    \\
    \\        pub fn set(self: *Self, value: T) void {
    \\            self.value = value;
    \\        }
    \\    };
    \\}
    \\
    \\/// Closure0 — M20h type-erased no-arg / void-return closure.
    \\///
    \\/// Each closure literal in Rig source generates a unique anonymous
    \\/// env struct (`RIG_CLOSURE_ENV_N`) holding its captures plus
    \\/// invoke/drop thunks tailored to those captures. The env is
    \\/// allocated separately from the surrounding `RcBox(Closure0)`;
    \\/// the env pointer is type-erased to `*anyopaque` so that
    \\/// `*Closure()` is a uniform handle type regardless of which
    \\/// literal produced it. That uniformity is what makes
    \\/// `*Closure()` returnable from functions, storable in struct
    \\/// fields, and aliasable through ordinary `+` / `<` / `~`.
    \\///
    \\/// `invoke(self)` jumps through the per-literal `invoke_fn` thunk
    \\/// (which knows the real env layout and calls the lambda body
    \\/// with captures threaded through).
    \\///
    \\/// `__rig_drop(self)` is the destructor hook honored by
    \\/// `RcBox(T).dropStrong()` on last strong: it calls the per-
    \\/// literal `drop_fn` thunk so capture-drops + env-free run at
    \\/// the right moment (NOT at each binding's scope-exit defer,
    \\/// which would UAF on `cb2 = +cb; -cb; cb2()`).
    \\pub const Closure0 = struct {
    \\    ctx: *anyopaque,
    \\    invoke_fn: *const fn (*anyopaque) void,
    \\    drop_fn: *const fn (*anyopaque, std.mem.Allocator) void,
    \\    allocator: std.mem.Allocator,
    \\
    \\    const Self = @This();
    \\
    \\    pub fn invoke(self: *Self) void {
    \\        self.invoke_fn(self.ctx);
    \\    }
    \\
    \\    /// Honored by `RcBox(Closure0).dropStrong()` via the
    \\    /// `hasRigDrop` predicate. Runs when the last strong handle
    \\    /// to the closure drops, before the control block is freed.
    \\    pub fn __rig_drop(self: *Self) void {
    \\        self.drop_fn(self.ctx, self.allocator);
    \\    }
    \\};
    \\
    \\/// PB3 + PB4: `Signal(T)` — multi-subscriber reactive primitive.
    \\///
    \\/// **Canary status (PB4, per GPT-5.5 entry 33).** Signal(T) is
    \\/// Rig's canary reactive primitive — NOT a long-term reactive
    \\/// API. Rust and Zig deliberately keep reactivity in libraries
    \\/// (Leptos / Dioxus / etc. on Rust; no ecosystem on Zig). Rig
    \\/// holds the same position: the SUBSTRATE (heap closures +
    \\/// resource Vec + Vec iteration + capture-resource audit)
    \\/// belongs in the language; reactive LIBRARIES (Reactor /
    \\/// Memo / Effect / batching) belong in userland once
    \\/// Cell-non-Copy or equivalent substrate lands. Signal is
    \\/// the minimum viable surface that forces the substrate to
    \\/// compose correctly. Do not extend Signal speculatively.
    \\///
    \\/// V1 restrictions:
    \\///   - `T` must be a Copy type (Int / Bool / Float / String /
    \\///     literal pseudo-types). Same as Cell. Non-Copy T would
    \\///     need replace/take/Drop semantics not yet in V1.
    \\///   - `Signal(T)` must be heap-owned via `*Signal(T)`. A
    \\///     stack-local `Signal(T)` would own a `Vec` without an
    \\///     M20e-style scope-exit guard wired through Signal's
    \\///     destructor. The sema-layer `checkSet` enforces the
    \\///     `*Signal(...)` shape per GPT-5.5's entry 29.
    \\///   - **Reentrant set is queued + coalesced (PB4).** A
    \\///     subscriber body that calls `signal.set(v)` on the same
    \\///     Signal does NOT recursively notify; the value is
    \\///     queued and runs in another notification round after
    \\///     the current walk completes. Multiple reentrant sets
    \\///     within one round coalesce to the most-recent value
    \\///     (latest wins). Iterative drain loop, NOT recursive —
    \\///     avoids stack growth on cascade chains.
    \\///   - **Reentrant subscribe still panics.** Adding
    \\///     subscribers from inside notification mutates the
    \\///     subscriber list mid-iteration; the queued-buffer-
    \\///     mutation semantics are subtler than set's queued
    \\///     value, and locking that policy would force a mini-
    \\///     Reactor design PB4 deliberately defers. Strict-first;
    \\///     relax later only if a canary forces it.
    \\///
    \\/// Lifecycle:
    \\///   - `init(value)`: construct with `subs = Vec.init(...)`.
    \\///     Called by the emit-side `tryEmitSignalConstruction`
    \\///     so the surface `*Signal(value: 0)` lowers to
    \\///     `rig.rcNew(rig.Signal(T).init(0))`.
    \\///   - `subscribe(cb)`: clones the incoming `*Closure()`
    \\///     handle and pushes it into `subs`. PANIC on reentry.
    \\///   - `set(value)`: if NOT notifying, run a drain loop that
    \\///     updates `value`, walks subscribers, then re-runs for
    \\///     any queued value until none remain. If notifying,
    \\///     queue the value (coalesce to latest) and return.
    \\///   - `__rig_drop`: cascades through `subs.__rig_drop()`,
    \\///     which walks elements LIFO and dropStrongs each
    \\///     retained closure handle (via M20i `dropElement`).
    \\///
    \\/// Iteration policy. The walk is by index with `len` snapshot
    \\/// at the start of each notification round; reentrant
    \\/// subscribe is still rejected, so `subs.len` and `subs.buf`
    \\/// are stable for the duration of any one round. The snapshot
    \\/// is cheap defense-in-depth.
    \\pub fn Signal(comptime T: type) type {
    \\    return struct {
    \\        value: T,
    \\        subs: Vec(*RcBox(Closure0)),
    \\        notifying: bool,
    \\        /// PB4: pending value queued by a reentrant `set`
    \\        /// call. Only meaningful when `pending_set = true`.
    \\        /// Coalesces to the most-recent reentrant value
    \\        /// within a notification cycle (latest wins).
    \\        pending_value: T,
    \\        pending_set: bool,
    \\
    \\        const Self = @This();
    \\
    \\        /// PB3 constructor (PB4 fields zero-init'd). Called by
    \\        /// emit's `tryEmitSignalConstruction` for the surface
    \\        /// form `*Signal(value: V)` ->
    \\        /// `rig.rcNew(rig.Signal(T).init(V))`. The Vec is
    \\        /// initialized empty with the default allocator; the
    \\        /// heap-owned `subs` buffer materializes on the first
    \\        /// `subscribe` call.
    \\        pub fn init(value: T) Self {
    \\            return .{
    \\                .value = value,
    \\                .subs = Vec(*RcBox(Closure0)).init(defaultAllocator()),
    \\                .notifying = false,
    \\                .pending_value = value,
    \\                .pending_set = false,
    \\            };
    \\        }
    \\
    \\        pub fn get(self: *const Self) T {
    \\            return self.value;
    \\        }
    \\
    \\        /// PB4 R2-relaxation: update the value AND invoke
    \\        /// every retained subscriber. Reentrant `set` from a
    \\        /// subscriber body queues the value (coalesce to most-
    \\        /// recent) instead of panicking; the outer drain loop
    \\        /// runs another notification round per queued value.
    \\        ///
    \\        /// Implementation is an iterative loop, NOT recursive
    \\        /// `self.set(v)` — recursion would re-enter the
    \\        /// notifying guard AND grow the stack proportionally
    \\        /// to cascade depth. The loop is bounded only by user
    \\        /// logic; a subscriber that always re-sets its own
    \\        /// Signal will loop forever (user-logic bug, not a
    \\        /// memory-safety issue).
    \\        ///
    \\        /// Iteration order: forwards (subscription order) per
    \\        /// the standard observer-pattern contract.
    \\        pub fn set(self: *Self, value: T) void {
    \\            if (self.notifying) {
    \\                // PB4 R2-relaxation: queue the value;
    \\                // coalesce to most-recent. The outer drain
    \\                // loop will pick this up after the current
    \\                // notification round completes.
    \\                self.pending_value = value;
    \\                self.pending_set = true;
    \\                return;
    \\            }
    \\            self.notifying = true;
    \\            defer self.notifying = false;
    \\            var next_value = value;
    \\            while (true) {
    \\                self.value = next_value;
    \\                const initial_len = self.subs.len;
    \\                if (self.subs.buf) |p| {
    \\                    var i: usize = 0;
    \\                    while (i < initial_len) : (i += 1) {
    \\                        p[i].value.invoke();
    \\                    }
    \\                }
    \\                if (!self.pending_set) break;
    \\                next_value = self.pending_value;
    \\                self.pending_set = false;
    \\            }
    \\        }
    \\
    \\        /// Register a subscriber. Clones the caller's
    \\        /// `*Closure()` handle and appends to `subs`. PANIC on
    \\        /// reentry — list-mutation semantics during iteration
    \\        /// are subtler than `set`'s queued value, and PB4
    \\        /// deliberately defers that policy. Strict-first;
    \\        /// relax later only if a canary forces it.
    \\        pub fn subscribe(self: *Self, cb: *RcBox(Closure0)) void {
    \\            if (self.notifying) @panic("Rig Signal.subscribe: subscribing during notification is not supported in V1");
    \\            self.subs.push(cb.cloneStrong());
    \\        }
    \\
    \\        /// M20h-style destructor hook: when the Signal's
    \\        /// containing RcBox hits last strong, cascade through
    \\        /// `subs.__rig_drop()` which walks elements LIFO and
    \\        /// dropStrongs each retained closure via the M20i
    \\        /// `dropElement` hybrid dispatch. `value` and
    \\        /// `pending_value` are Copy so no per-element drop is
    \\        /// needed.
    \\        pub fn __rig_drop(self: *Self) void {
    \\            self.subs.__rig_drop();
    \\        }
    \\    };
    \\}
    \\
    \\/// M20i: comptime predicate for the `dropElement` strong-handle
    \\/// branch. Returns true iff `T` is a single-element pointer to
    \\/// a struct declaring `__rig_rcbox_marker` (i.e., `T == *RcBox(U)`
    \\/// for some `U`). Pointer types can't declare `__rig_drop`, so
    \\/// we use shape-based dispatch on the pointee instead.
    \\pub fn isStrongHandle(comptime T: type) bool {
    \\    return switch (@typeInfo(T)) {
    \\        .pointer => |p| p.size == .one and
    \\            @typeInfo(p.child) == .@"struct" and
    \\            @hasDecl(p.child, "__rig_rcbox_marker"),
    \\        else => false,
    \\    };
    \\}
    \\
    \\/// M20i: drop a Vec element by inspecting its type at comptime.
    \\/// Hybrid dispatch per the M20i design pass:
    \\///
    \\///   1. `*RcBox(U)` strong handle (pointer type) \u2014 call
    \\///      `dropStrong()` on the value.
    \\///   2. Any value type with `__rig_drop` \u2014 call it.
    \\///   3. Else (Copy primitives, plain structs without a drop
    \\///      hook) \u2014 no-op.
    \\///
    \\/// Called by `Vec(T).clear` (in reverse order, LIFO) and
    \\/// `Vec(T).__rig_drop`. The comptime dispatch means the
    \\/// generated drop code for `Vec(i32)` (Copy element) is just
    \\/// `len = 0; free(buf)` \u2014 no per-element work at runtime.
    \\pub fn dropElement(comptime T: type, value: *T) void {
    \\    if (comptime isStrongHandle(T)) {
    \\        value.*.dropStrong();
    \\    } else if (comptime hasRigDrop(T)) {
    \\        value.__rig_drop();
    \\    }
    \\    // Copy/no-op branch: nothing to do.
    \\}
    \\
    \\/// M20i: `Vec(T)` \u2014 the resource-aware growable container.
    \\///
    \\/// Vec(T) is a resource VALUE TYPE (not a handle): it owns its
    \\/// backing buffer and is responsible for freeing both the
    \\/// elements (via `dropElement`) and the buffer itself when it
    \\/// drops. The Rig sema layer enforces that bare copy/alias of
    \\/// `Vec(T)` is rejected (would double-free); move via `<vec` is
    \\/// the only legal way to transfer ownership.
    \\///
    \\/// V1 element kinds: Copy primitives, `*T` shared handles, `~T`
    \\/// weak handles, `*Closure()`. Arbitrary nominal T is rejected
    \\/// at sema time until user-defined Drop exists.
    \\///
    \\/// Storage: `buf` is null when empty (`len == 0`, `cap == 0`)
    \\/// per `std.ArrayList` convention. First push allocates an
    \\/// initial capacity of 4; subsequent grows double the capacity.
    \\///
    \\/// Drop order: LIFO (last-pushed dropped first). Matches Zig
    \\/// `defer` ordering and Rust's `Drop` semantics for vectors.
    \\pub fn Vec(comptime T: type) type {
    \\    return struct {
    \\        allocator: std.mem.Allocator,
    \\        buf: ?[*]T,
    \\        len: usize,
    \\        cap: usize,
    \\
    \\        /// M20i: marker for the resource-aware-container family.
    \\        /// Not currently consumed (sema dispatches on the type
    \\        /// shape directly), but reserved for future dispatch.
    \\        pub const __rig_vec_marker = true;
    \\
    \\        const Self = @This();
    \\
    \\        pub fn init(allocator: std.mem.Allocator) Self {
    \\            return .{ .allocator = allocator, .buf = null, .len = 0, .cap = 0 };
    \\        }
    \\
    \\        pub fn initCapacity(allocator: std.mem.Allocator, capacity: usize) !Self {
    \\            if (capacity == 0) return init(allocator);
    \\            const buf = try allocator.alloc(T, capacity);
    \\            return .{ .allocator = allocator, .buf = buf.ptr, .len = 0, .cap = capacity };
    \\        }
    \\
    \\        fn ensureCapacity(self: *Self, min_cap: usize) !void {
    \\            if (self.cap >= min_cap) return;
    \\            const new_cap = if (self.cap == 0)
    \\                @max(min_cap, @as(usize, 4))
    \\            else
    \\                @max(min_cap, self.cap * 2);
    \\            const new_buf = try self.allocator.alloc(T, new_cap);
    \\            // Bitwise-move elements from old to new. Element drop
    \\            // semantics DO NOT fire here \u2014 the elements live in
    \\            // new_buf now; the old buffer is freed as raw storage.
    \\            if (self.buf) |old_ptr| {
    \\                if (self.len > 0) {
    \\                    @memcpy(new_buf[0..self.len], old_ptr[0..self.len]);
    \\                }
    \\                self.allocator.free(old_ptr[0..self.cap]);
    \\            }
    \\            self.buf = new_buf.ptr;
    \\            self.cap = new_cap;
    \\        }
    \\
    \\        /// Append `value` to the end. Panics on OOM (per M20d's
    \\        /// simple-API convention; fallible variant deferred).
    \\        pub fn push(self: *Self, value: T) void {
    \\            self.ensureCapacity(self.len + 1) catch @panic("Rig Vec allocation failed");
    \\            self.buf.?[self.len] = value;
    \\            self.len += 1;
    \\        }
    \\
    \\        /// Returns the current element count.
    \\        pub fn length(self: *const Self) usize {
    \\            return self.len;
    \\        }
    \\
    \\        /// Returns the element at index `i`, or null if `i >= len`.
    \\        /// V1: Copy T only \u2014 sema rejects `get` on resource T.
    \\        pub fn get(self: *const Self, i: usize) ?T {
    \\            if (i >= self.len) return null;
    \\            return self.buf.?[i];
    \\        }
    \\
    \\        /// Remove and return the last element, or null if empty.
    \\        /// V1: Copy T only \u2014 sema rejects `pop` on resource T
    \\        /// (returning `(*T)?` would need optional-resource auto-drop
    \\        /// semantics that don't exist yet).
    \\        pub fn pop(self: *Self) ?T {
    \\            if (self.len == 0) return null;
    \\            self.len -= 1;
    \\            return self.buf.?[self.len];
    \\        }
    \\
    \\        /// Drop all elements and reset `len` to 0. The backing
    \\        /// buffer is retained for reuse (use `__rig_drop` to free
    \\        /// the buffer too). Element drop is LIFO.
    \\        pub fn clear(self: *Self) void {
    \\            if (self.buf) |p| {
    \\                var i = self.len;
    \\                while (i > 0) {
    \\                    i -= 1;
    \\                    dropElement(T, &p[i]);
    \\                }
    \\            }
    \\            self.len = 0;
    \\        }
    \\
    \\        /// Destructor hook. Drops all elements (LIFO) and frees
    \\        /// the backing buffer. Invoked by:
    \\        ///   - `RcBox(Vec(T)).dropStrong()` on last strong
    \\        ///     (via `hasRigDrop` in M20h's hook).
    \\        ///   - Emit-side scope-exit defer-guard for stack-local
    \\        ///     `Vec(T)` bindings (M20i sub-commit (3-4/5)).
    \\        ///   - Explicit `-vec` in Rig source.
    \\        pub fn __rig_drop(self: *Self) void {
    \\            self.clear();
    \\            if (self.buf) |p| {
    \\                self.allocator.free(p[0..self.cap]);
    \\                self.buf = null;
    \\                self.cap = 0;
    \\            }
    \\        }
    \\    };
    \\}
    \\
    \\/// V1 default allocator for `*expr` boxes. Single-threaded, page-
    \\/// based. Later milestones may surface an allocator parameter; for
    \\/// V1 the runtime hides the choice so `*expr` is a one-liner in
    \\/// emitted Zig.
    \\pub fn defaultAllocator() std.mem.Allocator {
    \\    return std.heap.page_allocator;
    \\}
    \\
    \\/// Construct an `RcBox(T)` from a value, using the default allocator.
    \\/// Called by the emitter for `*expr` — the surrounding catch turns
    \\/// allocation failure into a panic (per the M20d design pass).
    \\pub fn rcNew(value: anytype) !*RcBox(@TypeOf(value)) {
    \\    return RcBox(@TypeOf(value)).new(defaultAllocator(), value);
    \\}
    \\
;
